# Generated by Django 4.1 on 2022-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addToCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='comments',
            field=models.CharField(max_length=360),
        ),
    ]
